conditioning:
  method: mpgd_wo_proj
  params:
    scale: 4

data:
  name: ffhq
  root: ../../data/images/

measurement:
  operator:
    name: gaussian_blur
    kernel_size: 81
    intensity: 5.0

  noise:
    name: gaussian
    sigma: 0.05

rewards:
  - name: adaface
    pretrained_model: ir_50
    steering: [search]
    data_path: '../../data/additional_images'
    scale: 1.0 # the scale for gradient

search_algorithm:
  name: group-meeting
  base: 4
  min_group: 2
  max_group: 8
  start_step: 100

num_particles: 8
